using System;
using System.Collections.Generic;

namespace MTAIntranet.Shared
{
    public partial class EqMain
    {
        public DateTime? XDatetimeInsert { get; set; }
        public string? XUseridInsert { get; set; }
        public int? DbAcc { get; set; }
        public int RowId { get; set; }
        public string? EqEquipNo { get; set; }
        public string? ClassClassMeter { get; set; }
        public string? ClassClassMaint { get; set; }
        public string? ClassClassPm { get; set; }
        public string? ClassClassStds { get; set; }
        public string? ClassClassRental { get; set; }
        public string? ClassClassShopSch { get; set; }
        public string? EqcatEquipCategory { get; set; }
        public string? DeptDeptCode { get; set; }
        public string? LocAssignPmLoc { get; set; }
        public string? LocAssignReprLoc { get; set; }
        public string? LocAssgnMobileLoc { get; set; }
        public string? AssocEquipNo { get; set; }
        public string? EqtypEquipType { get; set; }
        public string? PooltypVehType { get; set; }
        public int? Year { get; set; }
        public string? Manufacturer { get; set; }
        public string? Model { get; set; }
        public string? SerialNo { get; set; }
        public string? Description { get; set; }
        public string? Meter1Type { get; set; }
        public string? Meter2Type { get; set; }
        public string? Color { get; set; }
        public string? LicenseNo { get; set; }
        public string? LicenseSt { get; set; }
        public string? OperOperNo { get; set; }
        public string? OperName { get; set; }
        public string? StatusCodes { get; set; }
        public string? RadioNo { get; set; }
        public string? AssetNo { get; set; }
        public string? CpyCompanyCode { get; set; }
        public string? CostCenter { get; set; }
        public string? BillingCode { get; set; }
        public string? AcctAcctCode { get; set; }
        public decimal? ApprovalLevel { get; set; }
        public string? PriShopPriority { get; set; }
        public string? WorkOrderStatus { get; set; }
        public string? ReadyDisposition { get; set; }
        public string? LocStoredLoc { get; set; }
        public string? LocStationLoc { get; set; }
        public string? ParkingStall { get; set; }
        public int? FuelCardNo { get; set; }
        public string? CommentArea { get; set; }
        public string? Title { get; set; }
        public string? AuthorizationNo { get; set; }
        public decimal? OriginalCost { get; set; }
        public decimal? EstReplaceCost { get; set; }
        public int? EstReplaceYr { get; set; }
        public int? EstReplaceMo { get; set; }
        public string? ReplaceCode { get; set; }
        public DateTime? DateAdded { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? InServiceDate { get; set; }
        public int? Meter1AtDelivery { get; set; }
        public int? Meter2AtDelivery { get; set; }
        public int? Meter1PrevTotal { get; set; }
        public int? Meter2PrevTotal { get; set; }
        public string? OwnLeaseCustomer { get; set; }
        public decimal? MonthlyRent { get; set; }
        public DateTime? LeaseExpirationDt { get; set; }
        public decimal? FixedMonthlyCost { get; set; }
        public DateTime? OrigRegistDate { get; set; }
        public DateTime? RegistExpireDate { get; set; }
        public DateTime? RetireDate { get; set; }
        public DateTime? SaleDate { get; set; }
        public decimal? SalePrice { get; set; }
        public string? DisposalMethod { get; set; }
        public string? BuyBack { get; set; }
        public string? EqReplacedByUnit { get; set; }
        public string? EqReplacingUnit { get; set; }
        public string? PmProgType { get; set; }
        public DateTime? LastPmSchedDate { get; set; }
        public DateTime? LastPmStartDate { get; set; }
        public DateTime? NextPmSchedDate { get; set; }
        public string? InspectionMonth { get; set; }
        public int? StatInspectMonth { get; set; }
        public int? StatInspectYear { get; set; }
        public int? StatInspectInterv { get; set; }
        public int? LastPmSlot { get; set; }
        public int? NextPmSlot { get; set; }
        public int? LastPmMeter1 { get; set; }
        public int? LastPmMeter2 { get; set; }
        public int? PmMeter1Interval { get; set; }
        public int? PmMeter2Interval { get; set; }
        public int? PmFuelOverride { get; set; }
        public decimal? PmFuelSinceLast { get; set; }
        public string? PmPrefShift { get; set; }
        public string? OilType { get; set; }
        public string? TireType { get; set; }
        public int? QtyOpenWorkOrders { get; set; }
        public int? MonthsInOperation { get; set; }
        public int? QtyTires { get; set; }
        public string? FltFleetNo { get; set; }
        public int? LastMeter1Reading { get; set; }
        public int? LastMeter2Reading { get; set; }
        public DateTime? LastMeter1Date { get; set; }
        public DateTime? LastMeter2Date { get; set; }
        public string? LastMeterSource { get; set; }
        public string? LocLastFuelLoc { get; set; }
        public string? UsageTicketFlag { get; set; }
        public string? OffRoadUse { get; set; }
        public int? OffRoadPct { get; set; }
        public string? DepreciationMethod { get; set; }
        public int? DeprecMonthsLife { get; set; }
        public int? DeprMthsRemaining { get; set; }
        public decimal? DeprCurDeclineBal { get; set; }
        public int? SalvageValue { get; set; }
        public string? LocReservLoc { get; set; }
        public string? ReservStatus { get; set; }
        public DateTime? LastReservDateOut { get; set; }
        public DateTime? LastReservDateIn { get; set; }
        public int? LastReservMtrOut { get; set; }
        public int? LastReservMeterIn { get; set; }
        public string? ResvLastReservNo { get; set; }
        public string? ExceptionSwitches { get; set; }
        public string? CostRptExclSwitch { get; set; }
        public string? ExcpRptExclSwitch { get; set; }
        public string? InvListExclSwitch { get; set; }
        public decimal? FixedInsuranceCost { get; set; }
        public decimal? FixedReplaceCost { get; set; }
        public decimal? FixedLicensingCost { get; set; }
        public decimal? FixedCostOther1 { get; set; }
        public decimal? FixedCostOther2 { get; set; }
        public decimal? FixedCostOther3 { get; set; }
        public string? TaxTaxCode { get; set; }
        public decimal? SalvageValuePct { get; set; }
        public int? ReplCostComputed { get; set; }
        public int? ReplCostRecovYear { get; set; }
        public int? ReplCstTotrcovYr { get; set; }
        public int? ReplCstTotrcovLif { get; set; }
        public string? AcctRevAcctCode { get; set; }
        public string? DeptPmNotifyDept { get; set; }
        public string? CapitalCostPosted { get; set; }
        public string? WorkOrdersOk { get; set; }
        public string? FuelTicketsOk { get; set; }
        public string? UsageTicketsOk { get; set; }
        public int? MaxMeter1Value { get; set; }
        public int? MaxMeter2Value { get; set; }
        public string? CurOperIsFirst { get; set; }
        public decimal? BaseMrpCost { get; set; }
        public decimal? ActualCompanyCost { get; set; }
        public decimal? BaseMrpFirstOper { get; set; }
        public decimal? ActualCoFirstOper { get; set; }
        public decimal? ShippingCost { get; set; }
        public decimal? DutyCost { get; set; }
        public decimal? VatCost { get; set; }
        public string? LocCurrentLoc { get; set; }
        public string? SlaStatus { get; set; }
        public string? OnTempLoan { get; set; }
        public string? DeptTempLoanedTo { get; set; }
        public DateTime? TempLoanDate { get; set; }
        public string? DisposalReason { get; set; }
        public string? TransfereeName { get; set; }
        public string? TransfereeAddress1 { get; set; }
        public string? TransfereeAddress2 { get; set; }
        public string? TransfereeAddress3 { get; set; }
        public string? TransfereeAddress4 { get; set; }
        public string? InsInsuranceCode { get; set; }
        public DateTime? OrderDate { get; set; }
        public DateTime? PlannedDelivDate { get; set; }
        public DateTime? PlannedInsvcDate { get; set; }
        public DateTime? PlannedRetirDate { get; set; }
        public string? ProcstProcStatus { get; set; }
        public decimal? CapitalizedValue { get; set; }
        public DateTime? CapitalizedDate { get; set; }
        public DateTime? OLicenseDate { get; set; }
        public string? DisposalAuthority { get; set; }
        public string? DisposalComment { get; set; }
        public string? GreenDiskNo { get; set; }
        public DateTime? PlannedLicplDate { get; set; }
        public string? LicPlatingNo { get; set; }
        public string? HasTachograph { get; set; }
        public string? DielectricTesting { get; set; }
        public int? EstMeterAtReplace { get; set; }
        public string? UserStatus1 { get; set; }
        public string? UserStatus2 { get; set; }
        public string? UserStatus3 { get; set; }
        public string? StudyCode { get; set; }
        public decimal? OutfittingCost { get; set; }
        public string? OutfittingEffort { get; set; }
        public DateTime? LastRegularInspDt { get; set; }
        public DateTime? LastStatuteInspDt { get; set; }
        public DateTime? LastOilChangeDate { get; set; }
        public int? LastOilChangeMtr1 { get; set; }
        public int? LastOilChangeMtr2 { get; set; }
        public int? LifeTotalMeter1 { get; set; }
        public int? LifeTotalMeter2 { get; set; }
        public string? LicenseNo2 { get; set; }
        public string? MeterPostingFlag { get; set; }
        public DateTime? LastFuelDate { get; set; }
        public DateTime? LastYardckDatetime { get; set; }
        public string? YardckAvailRepair { get; set; }
        public string? IsTestEquip { get; set; }
        public string? LocAccessRtsLoc { get; set; }
        public string? CommentAreaMsg { get; set; }
        public string? RadioVehicleLoc { get; set; }
        public string? RadioBuildingLoc { get; set; }
        public string? RadioOtherLoc { get; set; }
        public string? ClassClassBench { get; set; }
        public string? FilePath { get; set; }
        public string? FileDescription { get; set; }
        public string? IsAsset { get; set; }
        public int? ParentLifeMeter1 { get; set; }
        public string? TrackParentMeter { get; set; }
        public string? RefEquipPos { get; set; }
        public string? LeaseLeaseId { get; set; }
        public decimal? LeaseResidualValue { get; set; }
        public int? CurrencyRowId { get; set; }
        public string? AssetType { get; set; }
        public string? AcatCategoryNo { get; set; }
        public string? EqInvalidated { get; set; }
        public string? EqEquipNoNew { get; set; }
        public string? AnyFuelType { get; set; }
        public string? LocSlaLoc { get; set; }
        public string? SysgrSystemGrouping { get; set; }
        public int? LastPmStartMeter1 { get; set; }
        public int? LastPmStartMeter2 { get; set; }
    }
}
